version: '3'
services:
  postgresql:
    build: .
    ports:
      - 15432:5432
    volumes:
      - postgres:/var/lib/postgresql/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  pgadmin4:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin4
    ports:
      - "8000:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root     # pgAdmin Address
      PGADMIN_DEFAULT_PASSWORD: root  # pgAdmin Password
    hostname: pgadmin4
    restart: always

volumes:
  postgres:
    name: postgres
    external: true
  pgadmin:
    name: pgadmin
    external: true
